import React from 'react';
import { 
  LayoutDashboard, 
  FolderTree, 
  Tag, 
  Package, 
  Ticket, 
  ShoppingCart, 
  Users, 
  Star, 
  Truck, 
  CreditCard,
  ChevronRight,
  ChevronDown,
  Loader,
  Folder,
  ChevronLeft,
  Plus, 
  Trash, 
  AlertCircle,
  Search,
  X,
  Filter,
  Edit,
  Eye,
  EyeOff,
  Save,
  Check,
  MoreVertical,
  Settings,
  Download,
  Upload,
  RefreshCw,
  Home,
  Archive,
  Activity,
  BarChart3,
  Calendar,
  Clock,
  User,
  Mail,
  Phone,
  MapPin,
  Globe,
  Link,
  Image,
  FileText,
  ShoppingBag,
  DollarSign,
  Percent,
  Hash,
  Type,
  Delete,
  Bold,
  Italic,
  List,
  ListOrdered,
  Quote,
  Code,
  Paperclip,
  Smile,
  Send,
  ThumbsUp,
  ThumbsDown,
  Heart,
  Share,
  Bookmark,
  Flag,
  MoreHorizontal,
  Menu,
  LogOut,
  Bell,
  Sun,
  Moon,
  Laptop,
  Wifi,
  WifiOff,
  Battery,
  BatteryCharging,
  Volume2,
  VolumeX,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Repeat,
  Shuffle,
  Mic,
  Headphones,
  Video,
  Camera,
  MicOff,
  VideoOff,
  MessageSquare,
  PhoneCall,
  Voicemail,
  Users as UsersIcon,
  UserPlus,
  UserCheck,
  UserX,
  Shield,
  Lock,
  Unlock,
  Key,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  Fingerprint,
  Smartphone,
  Tablet,
  Monitor,
  Server,
  Cloud,
  CloudOff,
  Database,
  HardDrive,
  Cpu,
  MemoryStick,
  Router,
  Wrench,
  Hammer,
  Ruler,
  Palette,
  Brush,
  Eraser,
  Crop,
  Filter as FilterIcon,
  Layers,
  Type as TypeIcon,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Bold as BoldIcon,
  Italic as ItalicIcon,
  Underline,
  Strikethrough,
  Subscript,
  Superscript,
  Pilcrow,
  WrapText,
  Minus,
  Divide,
  Square,
  Circle,
  Triangle,
  Hexagon,
  Octagon,
  Star as StarIcon,
  Heart as HeartIcon,
  ThumbsUp as ThumbsUpIcon,
  ThumbsDown as ThumbsDownIcon,
  CheckCircle,
  XCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  Ban,
  Radio,
  CheckSquare,
  Square as EmptySquare,
  ToggleLeft,
  ToggleRight,
  Sliders,
  Settings as SettingsIcon,
  Zap,
  ZapOff,
  Power,
  RotateCw,
  RefreshCw as RefreshCwIcon,
  Clock as ClockIcon,
  Calendar as CalendarIcon,
  Watch,
  Timer,
  Hourglass,
  Bell as BellIcon,
  BellOff,
  Megaphone,
  Speaker,
  Airplay,
  Cast,
  Bluetooth,
  Wifi as WifiIcon,
  Signal,
  SignalLow,
  SignalMedium,
  SignalHigh,
  Battery as BatteryIcon,
  BatteryLow,
  BatteryMedium,
  BatteryFull,
  BatteryWarning,
  Plug,
  Unplug,
  Flashlight,
  FlashlightOff,
  Printer,
  Webcam,
  Mouse,
  Keyboard,
  Gamepad,
  Joystick,
  Tv,
  Radio as RadioIcon,
  Mic as MicIcon,
  Headphones as HeadphonesIcon,
  Volume as VolumeIcon,
  Play as PlayIcon,
  Pause as PauseIcon,
  Rewind,
  FastForward,
  SkipBack as SkipBackIcon,
  SkipForward as SkipForwardIcon,
  Repeat as RepeatIcon,
  Shuffle as ShuffleIcon,
  Music,
  Video as VideoIcon,
  Film,
  Camera as CameraIcon,
  Image as ImageIcon,
  Palette as PaletteIcon,
  Contrast,
  Droplets,
  Sunset,
  Sun as SunIcon,
  Moon as MoonIcon,
  Cloud as CloudIcon,
  CloudRain,
  CloudSnow,
  CloudDrizzle,
  CloudLightning,
  CloudFog,
  Wind,
  Tornado,
  Thermometer,
  Umbrella,
  Snowflake,
  Leaf,
  Mountain,
  Navigation,
  Map,
  Compass,
  Globe as GlobeIcon,
  Anchor,
  Ship,
  Rocket,
  Plane,
  Car,
  Bike,
  Bus,
  Train,
  Truck as TruckIcon,
  Factory,
  Store,
  Building,
  Home as HomeIcon,
  Hotel,
  School,
  Church,
  Hospital,
  Briefcase,
  CreditCard as CreditCardIcon,
  DollarSign as DollarSignIcon,
  Euro,
  Bitcoin,
  Coins,
  Gem,
  Crown,
  Trophy,
  Medal,
  Target,
  Flag as FlagIcon,
  Shield as ShieldIcon,
  Sword,
  Skull,
  Ghost,
  Puzzle,
  Pyramid,
  Cylinder,
  Cone,
  Box,
  Grid,
  Layout,
  Sidebar,
  Navigation as NavigationIcon,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Move,
  RotateCw as RotateCwIcon,
  RotateCcw,
  ZoomIn,
  ZoomOut,
  Minimize,
  Maximize,
  Minus as MinusIcon,
  Plus as PlusIcon,
  X as XIcon,
  Divide as DivideIcon,
  Equal,
  Percent as PercentIcon,
  Hash as HashIcon,
  Infinity,
  Parentheses,
  Brackets,
  Braces,
  Sigma,
  Pi,
  Omega,
  Omega as OmegaIcon
} from 'lucide-react';

export const Icons = {
  // Navigation & Layout
  Dashboard: LayoutDashboard,
  ChevronRight: ChevronRight,
  ChevronDown: ChevronDown,
  ChevronLeft: ChevronLeft,
  Menu: Menu,
  MoreVertical: MoreVertical,
  MoreHorizontal: MoreHorizontal,
  Home: Home,
  // Catalog Management
  Categories: FolderTree,
  Brands: Tag,
  Products: Package,
  Folder: Folder,

  
  // Sales & Orders
  Orders: ShoppingCart,
  Coupons: Ticket,
  Customers: Users,
  ShoppingBag: ShoppingBag,
  DollarSign: DollarSign,
  Percent: Percent,
  
  // Content & Reviews
  Reviews: Star,
  Star: Star,
  
  // Shipping & Payments
  Shipping: Truck,
  Payments: CreditCard,
  Truck: Truck,
  CreditCard: CreditCard,
  
  // Actions
  Plus: Plus,
  Trash: Trash,
  Edit: Edit,
  Save: Save,
  Check: Check,
  X: X,
  Search: Search,
  Filter: Filter,
  Download: Download,
  Upload: Upload,
  RefreshCw: RefreshCw,

  
  
  // Status & Visibility
  Eye: Eye,
  EyeOff: EyeOff,
  AlertCircle: AlertCircle,
  AlertTriangle: AlertTriangle,
  CheckCircle: CheckCircle,
  XCircle: XCircle,
  Info: Info,
  HelpCircle: HelpCircle,
  Ban: Ban,



  // Loading & States
  Loader: Loader,
  Clock: Clock,
  Calendar: Calendar,
  
  // User & Auth
  User: User,
  Users: Users,
  UserPlus: UserPlus,
  UserCheck: UserCheck,
  UserX: UserX,
  LogOut: LogOut,
  Shield: Shield,
  Lock: Lock,
  Unlock: Unlock,
  
  // Files & Media
  Image: Image,
  FileText: FileText,
  Paperclip: Paperclip,
  
  // Settings & Configuration
  Settings: Settings,
  Wrench: Wrench,
  Sliders: Sliders,
  Zap: Zap,
  
  // Status Indicators
  Activity: Activity,
  BarChart3: BarChart3,
  Delete: Delete,
  
  // Additional for Category Management
  Archive: Archive,
  Globe: Globe,
  Link: Link,
  Type: Type,
  List: List,
  Grid: Grid,
  Layout: Layout,
  Sidebar: Sidebar,
  Move: Move,
  Copy: FileText, // Using FileText as copy icon
  ExternalLink: Link,
  
  // Status Badges
  Radio: Radio,
  CheckSquare: CheckSquare,
  EmptySquare: EmptySquare,
  ToggleLeft: ToggleLeft,
  ToggleRight: ToggleRight,
  
  // Pagination & Navigation
  ArrowUp: ArrowUp,
  ArrowDown: ArrowDown,
  ArrowLeft: ArrowLeft,
  ArrowRight: ArrowRight,
  
  // Bulk Actions
  SelectAll: CheckSquare,
  DeselectAll: EmptySquare,
  
  // Import/Export
  Import: Download,
  Export: Upload,
  
  // Hierarchy & Tree
  Leaf: Leaf,
  
  // SEO & Meta
  Code: Code,
  Hash: Hash,
  Tag: Tag,
  
  // Additional Utilities
  Bell: Bell,
  Mail: Mail,
  Phone: Phone,
  MapPin: MapPin,


};