// src/types/order.ts - Updated with invoice types

export interface OrderItem {
  _id: string;
  productType: 'product' | 'prebuilt-pc';
  product: {
    _id: string;
    name: string;
    images?: string[];
    slug?: string;
  };
  variant?: {
    variantId: string;
    name: string;
    sku: string;
    identifyingAttributes: Array<{
      key: string;
      label: string;
      value: string;
    }>;
  };
  name: string;
  sku: string;
  image?: string;
  quantity: number;
  originalPrice: number;
  discountedPrice: number;
  total: number;
  taxRate: number;
  taxAmount: number;
  returnable: boolean;
  returnWindow: number;
}

export interface ShippingAddress {
  firstName: string;
  lastName: string;
  email: string;
  phone?: string;
  address: string;
  city: string;
  state: string;
  country: string;
  zipCode: string;
  landmark?: string;
}

export interface Pricing {
  subtotal: number;
  shipping: number;
  tax: number;
  discount: number;
  total: number;
  currency: string;
  amountPaid: number;
  amountDue: number;
  totalSavings: number;
}

export interface PaymentAttempt {
  _id: string;
  razorpayOrderId: string;
  razorpayPaymentId?: string;
  razorpaySignature?: string;
  amount: number;
  currency: string;
  status: 'created' | 'attempted' | 'captured' | 'failed';
  gatewayPaymentMethod?: 'card' | 'upi' | 'netbanking' | 'wallet';
  gatewayResponse?: any;
  signatureVerified: boolean;
  errorReason?: string;
  razorpayExpiresAt?: Date;
  createdAt: Date;
  capturedAt?: Date;
}

export interface Payment {
  method: 'razorpay';
  status: 'created' | 'attempted' | 'captured' | 'failed';
  attempts: PaymentAttempt[];
  currentAttemptId?: string;
  lastAttemptAt?: Date;
  totalAttempts: number;
  retryAllowed: boolean;
}

export interface ShippingMethod {
  name: string;
  deliveryDays: number;
  cost: number;
  trackingNumber?: string;
  carrier?: string;
}

export interface ShippingEvent {
  _id: string;
  event: string;
  description?: string;
  location?: string;
  timestamp: Date;
  metadata?: any;
}

export interface TimelineEvent {
  _id: string;
  event: string;
  message: string;
  metadata: any;
  changedBy?: {
    _id: string;
    firstName: string;
    lastName: string;
  };
  changedAt: Date;
}

export interface Coupon {
  couponId: {
    _id: string;
    name: string;
    discountType: 'percentage' | 'fixed';
    discountAmount: number;
    maxDiscount?: number;
  };
  code: string;
  name?: string;
  discountType: 'percentage' | 'fixed';
  discountAmount: number;
  maxDiscount?: number;
}

export interface GSTInfo {
  gstNumber?: string;
  businessName?: string;
  businessAddress?: string;
  isBusiness: boolean;
}

export interface AdminNote {
  _id: string;
  note: string;
  addedBy: {
    _id: string;
    firstName: string;
    lastName: string;
  };
  addedAt: Date;
}

// NEW: Invoice Types
export interface AutoGeneratedInvoice {
  invoiceNumber?: string;
  pdfPath?: string;
  pdfUrl?: string;
  generatedAt?: Date;
  version?: number;
  status?: 'generated' | 'failed' | 'pending';
}

export interface AdminUploadedInvoice {
  invoiceNumber?: string;
  originalFileName?: string;
  pdfPath?: string;
  pdfUrl?: string;
  uploadedAt?: Date;
  uploadedBy?: {
    _id: string;
    firstName: string;
    lastName: string;
    email: string;
  };
  notes?: string;
  fileSize?: number;
  mimeType?: string;
}

export interface OrderInvoices {
  autoGenerated?: AutoGeneratedInvoice;
  adminUploaded?: AdminUploadedInvoice;
}

export interface InvoiceResponse {
  id: string;
  type: 'auto_generated' | 'admin_uploaded';
  title: string;
  invoiceNumber: string;
  pdfUrl: string;
  generatedAt?: Date;
  uploadedAt?: Date;
  uploadedBy?: any;
  notes?: string;
  fileSize?: number;
  source: 'system' | 'admin';
  canDownload: boolean;
  canDelete: boolean;
  version?: number;
  originalFileName?: string;
}

export interface Order {
  _id: string;
  orderNumber: string;
  user: {
    _id: string;
    firstName: string;
    lastName: string;
    email: string;
    phone?: string;
  };
  source: 'web' | 'mobile' | 'unknown';
  items: OrderItem[];
  shippingAddress: ShippingAddress;
  billingAddress: ShippingAddress;
  pricing: Pricing;
  payment: Payment;
  status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  shippingMethod: ShippingMethod;
  shippingEvents: ShippingEvent[];
  estimatedDelivery?: Date;
  deliveredAt?: Date;
  gstInfo?: GSTInfo;
  coupon?: Coupon;
  orderTimeline: TimelineEvent[];
  
  // UPDATED: Replace single invoice fields with invoices object
  invoices?: OrderInvoices;
  
  expiresAt?: Date;
  totalRefunded: number;
  adminNotes: AdminNote[];
  sendNotifications: boolean;
  fraudScore: number;
  riskFlags: string[];
  createdAt: Date;
  updatedAt: Date;
}

export interface OrderFilters {
  page?: number;
  limit?: number;
  status?: string;
  paymentStatus?: string;
  startDate?: string;
  endDate?: string;
  search?: string;
}

export interface OrderAnalytics {
  summary: {
    totalRevenue: number;
    totalOrders: number;
    averageOrderValue: number;
    successfulOrders: number;
  };
  ordersByStatus: Array<{
    _id: string;
    count: number;
  }>;
  revenueByDay: Array<{
    _id: string;
    revenue: number;
    orders: number;
  }>;
}

export interface OrderStatusUpdateData {
  status: string;
  trackingNumber?: string;
  carrier?: string;
  notes?: string;
  sendNotification?: boolean;
}

export interface ShippingUpdateData {
  trackingNumber: string;
  carrier: string;
  sendNotification?: boolean;
}

export interface AdminNoteFormData {
  note: string;
}

// NEW: Invoice related types
export interface InvoiceUploadData {
  invoiceNumber?: string;
  notes?: string;
}

export interface OrderFormData extends OrderStatusUpdateData {}